name: sqlhandler-odbc
version: '0.1.0.0'
github:              gbwey/sqlhandler-odbc
author: gbwey
maintainer: gbwey
copyright:           2019 Grant Weyburne
license: BSD3
# stack ghci --test --flag sqlhandler-odbc:my
flags:
  ms:
    description: run mssql th
    manual: yes
    default: no
  msold:
    description: run mssql th using an sqlserver pre 2012
    manual: yes
    default: no
  pg:
    description: run postgres th
    manual: yes
    default: no
  my:
    description: run mysql th
    manual: yes
    default: no
  oracle:
    description: run oracle th
    manual: yes
    default: no

dependencies:
- bytestring
- baseutils
- conduit
- containers
- pos >= 0.3.0.0
- primus >= 0.3.0.0
- database
- deepseq
- dhall >= 1.32.0
- docutils
- extra
- formatting
- Frames >= 0.6.1
- generic-lens
- generics-sop
- hdbc-odbc2
- lens
- logging-simple
- megaparsec
- monad-logger
- mtl
- pretty-simple
- prettyprinter
- replace-megaparsec
- resourcet
- safe
- semigroupoids
- shakespeare
- sqlhandler
- tagged
- template-haskell
- text
- th-compat
- these >= 1.0.0
- time
- unliftio
- uuid
- vinyl >= 0.10.0.0

default-extensions: []
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wno-star-is-type
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wunused-type-patterns
  - -Wredundant-constraints
  - -Wsimplifiable-class-constraints
  - -Wmonomorphism-restriction
  - -Wmissing-deriving-strategies
  - -Wmissing-local-signatures
  - -Widentities
  other-modules: []
  dependencies:
  - base >=4.7 && <=5.1

tests:
  spec:
    main: TestS3.hs
    ghc-options:
    - -threaded
    - -O0
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wunused-type-patterns
    - -Wredundant-constraints
    - -Wmissing-deriving-strategies
    - -Widentities
    - -Wno-missing-local-signatures
    source-dirs:
    - test/integration
    - test/unit
    dependencies:
      - base
      - sqlhandler-odbc
      - hspec
      - stm
      - tasty
      - tasty-hunit
      - unliftio-core
    when:
    - condition: flag(ms)
      other-modules: TestMS_TH
    - condition: flag(msold)
      other-modules: TestMSOld_TH
    - condition: flag(pg)
      other-modules: TestPG_TH
    - condition: flag(oracle)
      other-modules: TestOracle_TH
    - condition: flag(my)
      other-modules: TestMY_TH

data-files:
- conn.dhall
- coredb.dhall
- corems.dhall
- coremy.dhall
- corepg.dhall
- coreor.dhall
- cores3.dhall
- msdriver.dhall
- mydriver.dhall
- pgdriver.dhall
- ordriver.dhall
- s3driver.dhall
- log.dhall
- corelog.dhall