name: sqlhandler-odbc
version: '0.1.0.0'
author: Grant Weyburne
maintainer: gbwey9@gmail.com
license: BSD3
# stack ghci --test --flag sqlhandler-odbc:my
flags: 
  ms:
    description: run mssql th
    manual: yes
    default: no
  msold:
    description: run mssql th using an sqlserver pre 2012
    manual: yes
    default: no
  pg:
    description: run postgres th
    manual: yes
    default: no
  my:
    description: run mysql th
    manual: yes
    default: no
  oracle:
    description: run oracle th
    manual: yes
    default: no
  sqlite:
    description: run sqlite th
    manual: yes
    default: no
    
dependencies:
- unordered-containers
- bytestring
- clock
- conduit
- configurator
- containers
- directory
- extra
- fast-logger
- filepath
- foldl
- formatting
- Frames
- generics-sop
- ghc-prim
- HDBC == 2.4.0.3
- HDBC-odbc ==2.5.0.2
- iso8601-time
- lens
- lens-datetime
- mime-mail
- monad-logger
- mtl
- predicate
- regex-applicative
- resourcet
- semigroups
- shakespeare
- smtp-mail
- split
- sqlhandler
- tagged
- template-haskell
- text
- these
- time
- transformers
- typelevel
- unix-time >= 0.4.6
- unliftio
- unliftio-core
- uuid
- vinyl >= 0.10.0.0
- generic-lens
default-extensions: []
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  other-modules: []
  dependencies:
  - base >=4.7 && <=5.1

tests:
  spec:
    main: Spec.hs
    ghc-options: "-threaded -O0"
    source-dirs:
      - test/unit
    dependencies:
      - base
      - sqlhandler-odbc
      - hspec 
      - QuickCheck
      - easytest
    other-modules: 
     - TestDBConn
     - TestSqlParser

  testms_sp: 
    main: TestMS_SP_TH.hs
    source-dirs: test/integration
    when:
    - condition: flag(ms) 
      then:
        buildable: True
      else:
        buildable: False
    dependencies:
      - base
      - sqlhandler-odbc
    other-modules: TestConnections
    
  testms: 
    main: TestMS_TH.hs
    source-dirs: test/integration
    when:
    - condition: flag(msold) 
      then:
        buildable: True
      else:
        buildable: False
    dependencies:
      - base
      - sqlhandler-odbc
    other-modules: TestConnections

  testsqlite: 
    main: TestSqlite_TH.hs
    source-dirs: test/integration
    when:
    - condition: flag(sqlite) 
      then:
        buildable: True
      else:
        buildable: False
    dependencies:
      - base
      - sqlhandler-odbc
    other-modules: TestConnections

  testpg: 
    main: TestPG_TH.hs
    source-dirs: test/integration
    when:
    - condition: flag(pg) 
      then:
        buildable: True
      else:
        buildable: False
    dependencies:
      - base
      - sqlhandler-odbc
    other-modules: TestConnections

  testoracle: 
    main: TestOracle_TH.hs
    source-dirs: test/integration
    when:
    - condition: flag(oracle) 
      then:
        buildable: True
      else:
        buildable: False
    dependencies:
      - base
      - sqlhandler-odbc
    other-modules: TestConnections

  testmy: 
    main: TestMY_TH.hs
    source-dirs: test/integration
    when:
    - condition: flag(my) 
      then:
        buildable: True
      else:
        buildable: False
    dependencies:
      - base
      - sqlhandler-odbc
    other-modules: TestConnections


data-files: 
- db.cfg
