name: sqlhandler-odbc
version: '0.1.0.0'
author: Grant Weyburne
maintainer: gbwey9@gmail.com
license: BSD3
# stack ghci --test --flag sqlhandler-odbc:my
flags:
  ms:
    description: run mssql th
    manual: yes
    default: no
  msold:
    description: run mssql th using an sqlserver pre 2012
    manual: yes
    default: no
  pg:
    description: run postgres th
    manual: yes
    default: no
  my:
    description: run mysql th
    manual: yes
    default: no
  oracle:
    description: run oracle th
    manual: yes
    default: no

dependencies:
- bytestring
- containers
- dhall >= 1.27.0
- directory
- either
- safe
- formatting
- Frames >= 0.6.1
- generics-sop
- ghc-prim
- HDBC == 2.4.0.3
- HDBC-odbc == 2.5.0.2
- lens
- logging
- monad-logger
- mtl
- predicate
- predicate-typed
- regex-applicative
- resourcet
- semigroups
- shakespeare
- sqlhandler
- tagged
- template-haskell
- text
- these >= 1.0
- time
- typelevel
- unix-time >= 0.4.6
- unliftio
- uuid
- vinyl >= 0.10.0.0

default-extensions: []
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fomit-interface-pragmas
  other-modules: []
  dependencies:
  - base >=4.7 && <=5.1

tests:
  spec:
    main: TestS3.hs
    ghc-options:
    - -threaded
    - -O0
    - -fomit-interface-pragmas
    source-dirs:
    - test/integration
    - test/unit
    dependencies:
      - base
      - sqlhandler-odbc
      - hspec
      - QuickCheck
      - tasty
      - tasty-hunit
      - tasty-quickcheck
    other-modules:
    - TestConnections
    - TestSqlite_TH
    - TestDBConn
    - TestSqlParser
    - Spec
    when:
    - condition: flag(ms)
      other-modules: TestMS_TH
    - condition: flag(msold)
      other-modules: TestMSOld_TH
    - condition: flag(pg)
      other-modules: TestPG_TH
    - condition: flag(oracle)
      other-modules: TestOracle_TH
    - condition: flag(my)
      other-modules: TestMY_TH

data-files:
- conn.dhall
- coreconn.dhall
- log.dhall
- corelog.dhall