flags: {}
extra-package-dbs: []
packages:
- location: '.'
- location: ../logging
  extra-dep: true
- location: ../hdbc
  extra-dep: true
- location: ../hdbc-odbc
  extra-dep: true
- location: ../table-layout
  extra-dep: true
- location: ../predicate
  extra-dep: true
- location: ../typelevel
  extra-dep: true
- location: ../predicate-typed
  extra-dep: true
- location: ../sqlhandler
  extra-dep: true
extra-deps:
- pretty-terminal-0.1.0.0
- pretty-tree-0.1.0.0
- tree-view-0.5
- Frames-0.6.1
- symbols-0.3.0.0
- discrimination-0.4
- dhall-1.27.0
- these-lens-1
- smtp-mail-0.2.0.0

arch: x86_64
resolver: lts-14.10

# ghc-options: {"$locals": -ddump-to-file -ddump-hi}