resolver: lts-14.10
packages:
- '.'
extra-deps:
- pretty-terminal-0.1.0.0
- tree-view-0.5
- Frames-0.6.1
- discrimination-0.4
- symbols-0.3.0.0
- dhall-1.27.0
- smtp-mail-0.2.0.0
- ../database
- ../logging
- ../hdbc-odbc2
- ../table-layout
- ../typelevel
- ../predicate-typed
- ../sqlhandler

# ghc-options: {"$locals": -ddump-to-file -ddump-hi}