resolver: lts-18.10
packages:
- '.'
extra-deps:
- Frames-0.7.2
- discrimination-0.4.1
- ../baseutils
- ../pos
- ../primus
# - pos-0.3.0.0
# - primus-0.3.0.0
- ../docutils
- ../database
- ../logging-simple
- ../hdbc-odbc2
- ../table-layout
- ../sqlhandler
