resolver: lts-18.10
packages:
- '.'
extra-deps:
- Frames-0.7.2
- discrimination-0.4.1
- ../baseutils
- ../coreutils
- ../docutils
- ../database
- ../logging-simple
- ../hdbc-odbc2
- ../table-layout
- ../sqlhandler

# ghc-options: {"$locals": -ddump-to-file -ddump-hi}

#ghc-options:
#  "$locals": -fwrite-ide-info
#  "$everything": -haddock
