resolver: lts-14.10
packages:
- '.'
extra-deps:
- pretty-terminal-0.1.0.0
- tree-view-0.5
- Frames-0.6.1
- discrimination-0.4
- symbols-0.3.0.0
- dhall-1.28.0
- atomic-write-0.2.0.7@sha256:3b626dfbc288cd070f1ac31b1c15ddd49822a923778ffe21f92b2116ffc72dc3,4584
- prettyprinter-1.5.1@sha256:fca87c3e2611d3499a0341a59857e9b424a23f31646e4737d535a18582284f96,5375
- smtp-mail-0.2.0.0
- ../database
- ../logging
- ../hdbc-odbc2
- ../table-layout
- ../typelevel
- ../predicate-typed
- ../sqlhandler

# ghc-options: {"$locals": -ddump-to-file -ddump-hi}