flags: {}
extra-package-dbs: []
packages:
- location: '.'
- location: ../logging
  extra-dep: true
- location: ../hdbc
  extra-dep: true
- location: ../hdbc-odbc
  extra-dep: true
- location: ../table-layout
  extra-dep: true
- location: ../predicate
  extra-dep: true
- location: ../typelevel
  extra-dep: true
- location: ../predicate-typed
  extra-dep: true
- location: ../sqlhandler
  extra-dep: true
extra-deps:
- pretty-terminal-0.1.0.0
- pretty-tree-0.1.0.0
- tree-view-0.5
- Frames-0.6.1
- symbols-0.2.0.1
- unix-time-0.4.6
- discrimination-0.4
- dhall-1.26.0
- th-lift-instances-0.1.14
- th-lift-0.8.0.1

arch: x86_64
resolver: lts-13.25

# ghc-options: {"$locals": -ddump-to-file -ddump-hi}